---
# http://dev.mysql.com/doc/refman/5.6/en/cannot-initialize-character-set.html
{{ set mysql_ver = mysql_ver | default('5.6') %}}
- name: Install MySQL
  yum: name={{ item }} state=installed
  with_items:
    - rpm: MySQL-client-{{ mysql_ver }}.el6.x86_64.rpm
    - rpm: MySQL-shared-compat-{{ mysql_ver }}.el6.x86_64.rpm
    - rpm: MySQL-shared-{{ mysql_ver }}.el6.x86_64.rpm
    - rpm: MySQL-devel-{{ mysql_ver }}.el6.x86_64.rpm
    - rpm: MySQL-server-{{ mysql_ver }}.el6.x86_64.rpm
    - MySQL-python
  tags: mysqld

- name: Run MySQL
  service: name=mysqld state=running enabled=yes
  tags: mysqld

- name: Create root account
  mysql_user:
    name: root
    host: localhost
    # password: "{{ mysql_root_password }}"

- name: Setup config file
  template:
    src: templates/my.cnf.j2
    dest: "/root/my.cnf"
    mode: 0600
